# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Cards CR Hiberus' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'R.swift'
  pod 'RxSwift',    '~> 4.0'
  pod 'RxCocoa',    '~> 4.0'
  pod 'Moya/RxSwift', '13.0.0'
  pod 'Kingfisher', '~> 5.5'

  target 'Cards CR HiberusTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
